# Generated by Django 3.0 on 2019-12-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptography', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bosy',
            new_name='body',
        ),
    ]
