# Generated by Django 3.0 on 2020-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptography', '0005_auto_20200103_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
