# Generated by Django 3.0 on 2020-01-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_auto_20200104_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
